import type {
  ActionItem,
  Advisor,
  Integration,
  Intervention,
  JobVacancy,
  Note,
  Participant,
  ProgrammeKpis,
  WorkflowTask,
} from "./types";

const n = (
  author: string,
  at: string,
  body: string,
  source: Note["source"] = "advisor",
): Note => ({
  id: `${author}-${at}`,
  at,
  author,
  body,
  source,
});

const act = (
  id: string,
  title: string,
  due: string,
  owner: ActionItem["owner"],
  done = false,
): ActionItem => ({ id, title, due, owner, done });

export const ADVISORS: Advisor[] = [
  {
    id: "adv-sarah",
    name: "Sarah Bell",
    role: "Employment Advisor",
    centre: "Manchester",
    caseloadTarget: 55,
  },
  {
    id: "adv-marcus",
    name: "Marcus Reid",
    role: "Employment Advisor",
    centre: "Birmingham",
    caseloadTarget: 50,
  },
  {
    id: "adv-leila",
    name: "Leila Hassan",
    role: "Employment Advisor",
    centre: "London",
    caseloadTarget: 48,
  },
];

export const DEMO_PARTICIPANT_ID = "p-amina";
export const DEMO_ADVISOR_ID = "adv-sarah";

export const PARTICIPANTS: Participant[] = [
  {
    id: "p-amina",
    firstName: "Amina",
    lastName: "Rahman",
    preferredName: "Amina",
    age: 29,
    pronouns: "she/her",
    centre: "Manchester",
    localAuthority: "Manchester",
    advisorId: "adv-sarah",
    programme: "Future Employment Support",
    ucStatus: "Universal Credit — intensive work search",
    referralSource: "Jobcentre Plus · PRaP",
    referralDate: "2026-07-14",
    stage: "support",
    risk: "medium",
    barriers: [
      { id: "b1", label: "Childcare around school hours", kind: "non-vocational" },
      { id: "b2", label: "Confidence after a long gap", kind: "non-vocational" },
      { id: "b3", label: "Digital skills — spreadsheets & ATS", kind: "vocational" },
    ],
    assessment: { life: 62, skills: 54, work: 48, aspirations: 78 },
    goal: "Part-time office administration, with a path into HR support",
    availability: "Term-time, 09:30–14:30",
    lastContact: "2026-09-12",
    nextAction: "Review admin job shortlist and book mock interview",
    daysOnProgramme: 65,
    jobsApplied: 7,
    interviews: 1,
    engagement: 81,
    phone: "07700 900 214",
    email: "amina.r@example.test",
    plan: "Build a school-hours admin CV, complete Excel fundamentals, and practise a structured interview for reception / office roles in Greater Manchester.",
    cvSummary:
      "Reliable administrator returning to work after caring for my daughter. Experience in reception, diary management and customer-facing roles. Looking for part-time office work in Manchester.",
    notes: [
      n(
        "Sarah Bell",
        "2026-09-12",
        "Amina is more settled on childcare. Keen on school-hours admin. Agreed to apply to three vacancies this week and practise a competency answer for 'working under pressure'.",
      ),
      n(
        "Sarah Bell",
        "2026-08-21",
        "Initial assessment complete. Highest pillar is aspirations — she knows the kind of work she wants. Work-readiness is the gap: routine, CV, and interview nerves.",
      ),
    ],
    actions: [
      act("a1", "Apply to two school-hours admin roles", "2026-09-19", "participant"),
      act("a2", "Complete Excel essentials module", "2026-09-24", "participant"),
      act("a3", "Book 20-minute mock interview", "2026-09-18", "advisor"),
    ],
  },
  {
    id: "p-james",
    firstName: "James",
    lastName: "Okafor",
    preferredName: "James",
    age: 42,
    pronouns: "he/him",
    centre: "Birmingham",
    localAuthority: "Birmingham",
    advisorId: "adv-marcus",
    programme: "Future Employment Support",
    ucStatus: "Universal Credit",
    referralSource: "Jobcentre Plus",
    referralDate: "2026-05-02",
    stage: "job-search",
    risk: "low",
    barriers: [
      { id: "b1", label: "Long-term back condition — standing limits", kind: "non-vocational" },
      { id: "b2", label: "Supervisor experience not on current CV", kind: "vocational" },
    ],
    assessment: { life: 71, skills: 76, work: 68, aspirations: 64 },
    goal: "Warehouse team leader or logistics coordinator, sitting-friendly",
    availability: "Full-time, days",
    lastContact: "2026-09-15",
    nextAction: "Employer intro — DHL Bordesley Green",
    daysOnProgramme: 138,
    jobsApplied: 22,
    interviews: 4,
    engagement: 74,
    phone: "07700 900 331",
    email: "j.okafor@example.test",
    plan: "Target team-leader vacancies with reasonable adjustments noted. Evidence supervisory experience from 2016–2022.",
    cvSummary:
      "Logistics professional with 12 years in warehousing including two years as acting team leader. Strong on rotas, health and safety, and keeping a shift moving.",
    notes: [
      n(
        "Marcus Reid",
        "2026-09-15",
        "James is interview-ready. Needs roles that are not all-standing. DHL have a coordinator vacancy — sending a warm intro tomorrow.",
      ),
    ],
    actions: [
      act("j1", "Send DHL coordinator application", "2026-09-18", "participant"),
      act("j2", "Confirm Access to Work conversation", "2026-09-22", "advisor"),
    ],
  },
  {
    id: "p-chloe",
    firstName: "Chloe",
    lastName: "Price",
    preferredName: "Chloe",
    age: 19,
    pronouns: "she/her",
    centre: "London",
    localAuthority: "Hackney",
    advisorId: "adv-leila",
    programme: "Future Employment Support · Youth",
    ucStatus: "Youth — not in education, employment or training",
    referralSource: "Youth Hub",
    referralDate: "2026-09-04",
    stage: "onboarding",
    risk: "medium",
    barriers: [
      { id: "b1", label: "No paid work history", kind: "vocational" },
      { id: "b2", label: "Anxiety in new settings", kind: "non-vocational" },
    ],
    assessment: { life: 58, skills: 41, work: 28, aspirations: 66 },
    goal: "Retail or hospitality with a route into events",
    availability: "Flexible, including weekends",
    lastContact: "2026-09-08",
    nextAction: "Complete joint pledge and first assessment",
    daysOnProgramme: 13,
    jobsApplied: 0,
    interviews: 0,
    engagement: 44,
    phone: "07700 900 118",
    email: "chloe.p@example.test",
    plan: "",
    cvSummary: "",
    notes: [
      n(
        "Leila Hassan",
        "2026-09-08",
        "Warm first meeting. Chloe wants events work but is open to retail as a start. Keep sessions short and predictable.",
      ),
    ],
    actions: [
      act("c1", "Finish onboarding forms", "2026-09-18", "participant"),
      act("c2", "Book assessment session", "2026-09-19", "advisor"),
    ],
  },
  {
    id: "p-david",
    firstName: "David",
    lastName: "Chen",
    preferredName: "David",
    age: 51,
    pronouns: "he/him",
    centre: "Manchester",
    localAuthority: "Salford",
    advisorId: "adv-sarah",
    programme: "Future Employment Support",
    ucStatus: "Off UC — in work",
    referralSource: "Jobcentre Plus",
    referralDate: "2026-03-11",
    stage: "employed",
    risk: "low",
    barriers: [
      { id: "b1", label: "Age bias in previous applications", kind: "vocational" },
    ],
    assessment: { life: 80, skills: 72, work: 84, aspirations: 70 },
    goal: "Care assistant — nights, local",
    availability: "Nights",
    lastContact: "2026-09-09",
    nextAction: "Week-4 in-work check-in",
    daysOnProgramme: 190,
    jobsApplied: 11,
    interviews: 3,
    engagement: 69,
    phone: "07700 900 441",
    email: "d.chen@example.test",
    outcome: {
      employer: "Salford Care Partnership",
      role: "Night care assistant",
      startDate: "2026-08-18",
      hours: 28,
      wage: "£12.60 / hour",
      sustainmentWeek: 4,
    },
    plan: "In-work support through first 13 weeks. Check rota, travel, and confidence with night medication rounds.",
    cvSummary:
      "Patient, steady care assistant. Previous retail management transferable to coordinating a night team.",
    notes: [
      n(
        "Sarah Bell",
        "2026-09-09",
        "David is enjoying nights. A little tired in week 4 — normal. Employer contact is positive. Flag 13-week evidence pack.",
      ),
    ],
    actions: [
      act("d1", "Week-4 wellbeing check", "2026-09-18", "advisor", true),
      act("d2", "Collect 13-week evidence", "2026-11-16", "advisor"),
    ],
  },
  {
    id: "p-fatima",
    firstName: "Fatima",
    lastName: "Ali",
    preferredName: "Fatima",
    age: 34,
    pronouns: "she/her",
    centre: "London",
    localAuthority: "Tower Hamlets",
    advisorId: "adv-leila",
    programme: "Future Employment Support",
    ucStatus: "Universal Credit",
    referralSource: "Talking Therapies · EA referral",
    referralDate: "2026-06-20",
    stage: "intervention",
    risk: "medium",
    barriers: [
      { id: "b1", label: "English for the workplace (ESOL L1)", kind: "vocational" },
      { id: "b2", label: "Temporary housing", kind: "non-vocational" },
    ],
    assessment: { life: 44, skills: 61, work: 50, aspirations: 82 },
    goal: "Healthcare support worker",
    availability: "Days, school hours preferred",
    lastContact: "2026-09-11",
    nextAction: "Care Certificate unit 2 + housing officer update",
    daysOnProgramme: 89,
    jobsApplied: 4,
    interviews: 0,
    engagement: 77,
    phone: "07700 900 552",
    email: "fatima.ali@example.test",
    plan: "Stabilise housing, complete Care Certificate units, then target NHS band 2 support worker vacancies.",
    cvSummary:
      "Caring, calm, and organised. Informal caring experience plus ESOL study. Aiming for healthcare support work.",
    notes: [
      n(
        "Leila Hassan",
        "2026-09-11",
        "Housing officer meeting Thursday. Fatima is thriving in the Care Certificate group — keep that going even if housing is noisy.",
      ),
    ],
    actions: [
      act("f1", "Attend Care Certificate session", "2026-09-18", "participant"),
      act("f2", "Liaise with housing officer", "2026-09-19", "advisor"),
    ],
  },
  {
    id: "p-ryan",
    firstName: "Ryan",
    lastName: "Hughes",
    preferredName: "Ryan",
    age: 27,
    pronouns: "he/him",
    centre: "Manchester",
    localAuthority: "Tameside",
    advisorId: "adv-sarah",
    programme: "Future Employment Support",
    ucStatus: "Universal Credit",
    referralSource: "Probation · ETE",
    referralDate: "2026-09-10",
    stage: "referral",
    risk: "high",
    barriers: [
      { id: "b1", label: "Unspent conviction — disclosure needed", kind: "vocational" },
      { id: "b2", label: "No current ID documents", kind: "non-vocational" },
    ],
    assessment: { life: 38, skills: 47, work: 22, aspirations: 55 },
    goal: "Construction labourer, CSCS route",
    availability: "Full-time, early starts",
    lastContact: "2026-09-10",
    nextAction: "First appointment — ID, disclosure, CSCS plan",
    daysOnProgramme: 7,
    jobsApplied: 0,
    interviews: 0,
    engagement: 20,
    phone: "07700 900 673",
    email: "ryan.h@example.test",
    plan: "",
    cvSummary: "",
    notes: [
      n(
        "Sarah Bell",
        "2026-09-10",
        "Referral received from probation. Three contact attempts scheduled. Ban the box employers first.",
      ),
    ],
    actions: [
      act("r1", "Attend first appointment", "2026-09-18", "participant"),
      act("r2", "Start ID document pack", "2026-09-18", "advisor"),
    ],
  },
  {
    id: "p-priya",
    firstName: "Priya",
    lastName: "Shah",
    preferredName: "Priya",
    age: 38,
    pronouns: "she/her",
    centre: "Birmingham",
    localAuthority: "Birmingham",
    advisorId: "adv-marcus",
    programme: "Future Employment Support",
    ucStatus: "Universal Credit — limited capability for work-related activity review",
    referralSource: "Jobcentre Plus",
    referralDate: "2026-04-16",
    stage: "support",
    risk: "medium",
    barriers: [
      { id: "b1", label: "Anxiety and low mood", kind: "non-vocational" },
      { id: "b2", label: "Caring for parent three days a week", kind: "non-vocational" },
    ],
    assessment: { life: 51, skills: 80, work: 42, aspirations: 60 },
    goal: "Part-time bookkeeping or finance admin",
    availability: "Tue / Thu / Fri, 09:00–15:00",
    lastContact: "2026-09-04",
    nextAction: "Overdue contact — wellbeing and AAT progress",
    daysOnProgramme: 154,
    jobsApplied: 3,
    interviews: 0,
    engagement: 52,
    phone: "07700 900 884",
    email: "priya.shah@example.test",
    plan: "Keep AAT foundation moving at a gentle pace. Do not push volume of applications. Protect caring days.",
    cvSummary:
      "Qualified to AAT Level 2 (in progress). Previously finance assistant in a GP practice. Accurate, discreet, good with people who are stressed.",
    notes: [
      n(
        "Marcus Reid",
        "2026-08-20",
        "Priya cancelled last two sessions. Mood lower. Keep the door open — a text check-in rather than a formal DNA for now.",
      ),
    ],
    actions: [
      act("pr1", "Advisor wellbeing check-in", "2026-09-17", "advisor"),
      act("pr2", "AAT module 3 practice paper", "2026-09-30", "participant"),
    ],
  },
  {
    id: "p-tomasz",
    firstName: "Tomasz",
    lastName: "Kowalski",
    preferredName: "Tomek",
    age: 45,
    pronouns: "he/him",
    centre: "London",
    localAuthority: "Newham",
    advisorId: "adv-leila",
    programme: "Future Employment Support",
    ucStatus: "Universal Credit",
    referralSource: "Jobcentre Plus",
    referralDate: "2026-02-03",
    stage: "job-search",
    risk: "low",
    barriers: [
      { id: "b1", label: "Workplace English — written", kind: "vocational" },
      { id: "b2", label: "No car — needs depot on a bus route", kind: "non-vocational" },
    ],
    assessment: { life: 73, skills: 69, work: 77, aspirations: 58 },
    goal: "HGV Class 2 driver",
    availability: "Full-time, early",
    lastContact: "2026-09-14",
    nextAction: "Two local depot applications + licence check",
    daysOnProgramme: 227,
    jobsApplied: 18,
    interviews: 2,
    engagement: 70,
    phone: "07700 900 229",
    email: "t.kowalski@example.test",
    plan: "Passed C+E medical. Target Newham / Barking depots with bus access. Pair with a written-English check on application forms.",
    cvSummary:
      "Experienced driver. Forklift and warehouse background. Reliable early starter. Licence clean.",
    notes: [
      n(
        "Leila Hassan",
        "2026-09-14",
        "Tomek is close. One interview last month stalled on a written test. Practise form language this week.",
      ),
    ],
    actions: [
      act("t1", "Apply to two bus-route depots", "2026-09-20", "participant"),
    ],
  },
  {
    id: "p-nia",
    firstName: "Nia",
    lastName: "Williams",
    preferredName: "Nia",
    age: 23,
    pronouns: "she/they",
    centre: "Manchester",
    localAuthority: "Manchester",
    advisorId: "adv-sarah",
    programme: "Future Employment Support · Youth",
    ucStatus: "Universal Credit",
    referralSource: "Jobcentre Plus",
    referralDate: "2026-08-01",
    stage: "assessment",
    risk: "medium",
    barriers: [
      { id: "b1", label: "Autism — noisy open offices difficult", kind: "non-vocational" },
      { id: "b2", label: "Interview anxiety", kind: "non-vocational" },
    ],
    assessment: { life: 64, skills: 86, work: 35, aspirations: 74 },
    goal: "IT support or junior data role, remote or quiet office",
    availability: "Full-time, remote preferred",
    lastContact: "2026-09-13",
    nextAction: "Finish assessment and agree reasonable adjustments",
    daysOnProgramme: 47,
    jobsApplied: 2,
    interviews: 0,
    engagement: 88,
    phone: "07700 900 910",
    email: "nia.w@example.test",
    plan: "Capture a clear adjustments profile. Use structured interview practice. Target employers with Disability Confident Leader status.",
    cvSummary:
      "CompTIA ITF+ and a distinction in BTEC IT. Built a helpdesk ticketing spreadsheet for a local charity. Looking for a first IT support role.",
    notes: [
      n(
        "Sarah Bell",
        "2026-09-13",
        "Nia is highly skilled and honest about sensory load. Do not send to walk-in retail IT. Written applications first.",
      ),
    ],
    actions: [
      act("n1", "Complete four-pillar assessment", "2026-09-18", "participant"),
      act("n2", "Draft adjustments one-pager", "2026-09-20", "advisor"),
    ],
  },
  {
    id: "p-michael",
    firstName: "Michael",
    lastName: "Grant",
    preferredName: "Mick",
    age: 58,
    pronouns: "he/him",
    centre: "Birmingham",
    localAuthority: "Sandwell",
    advisorId: "adv-marcus",
    programme: "Future Employment Support",
    ucStatus: "Universal Credit",
    referralSource: "Jobcentre Plus",
    referralDate: "2026-01-20",
    stage: "intervention",
    risk: "medium",
    barriers: [
      { id: "b1", label: "COPD — outdoor winter work limited", kind: "non-vocational" },
      { id: "b2", label: "Digital exclusion — no home broadband", kind: "vocational" },
    ],
    assessment: { life: 56, skills: 60, work: 63, aspirations: 49 },
    goal: "Facilities or groundskeeping, days, local",
    availability: "Days, not winter nights",
    lastContact: "2026-09-07",
    nextAction: "Library digital session + council estates vacancy",
    daysOnProgramme: 240,
    jobsApplied: 9,
    interviews: 1,
    engagement: 41,
    phone: "07700 900 304",
    email: "m.grant@example.test",
    plan: "Use the centre and library for applications. Prefer outdoor/day roles with a vehicle provided.",
    cvSummary:
      "Thirty years in factories and yards. Handy, punctual, good with plant. Looking for a local facilities or grounds role.",
    notes: [
      n(
        "Marcus Reid",
        "2026-09-07",
        "Mick will not apply from a phone. Book the Thursday library slot and sit with him.",
      ),
    ],
    actions: [
      act("m1", "Library application session", "2026-09-18", "advisor"),
    ],
  },
  {
    id: "p-sophie",
    firstName: "Sophie",
    lastName: "Bennett",
    preferredName: "Sophie",
    age: 31,
    pronouns: "she/her",
    centre: "London",
    localAuthority: "Hackney",
    advisorId: "adv-leila",
    programme: "Future Employment Support",
    ucStatus: "Off UC — in work",
    referralSource: "Jobcentre Plus",
    referralDate: "2025-12-02",
    stage: "sustainment",
    risk: "low",
    barriers: [],
    assessment: { life: 84, skills: 78, work: 88, aspirations: 81 },
    goal: "Teaching assistant — achieved",
    availability: "Term-time",
    lastContact: "2026-09-02",
    nextAction: "13-week sustainment evidence signed off",
    daysOnProgramme: 289,
    jobsApplied: 14,
    interviews: 5,
    engagement: 60,
    phone: "07700 900 615",
    email: "s.bennett@example.test",
    outcome: {
      employer: "Stoke Newington Primary",
      role: "Teaching assistant",
      startDate: "2026-06-02",
      hours: 32,
      wage: "£24,400 FTE",
      sustainmentWeek: 15,
    },
    plan: "Light-touch sustainment. Check in at 26 weeks unless the school raises a concern.",
    cvSummary: "Teaching assistant with SEN experience in a Hackney primary.",
    notes: [
      n(
        "Leila Hassan",
        "2026-09-02",
        "13-week outcome evidenced. Sophie is thriving. Schedule 26-week check.",
      ),
    ],
    actions: [
      act("s1", "26-week sustainment check", "2026-12-01", "advisor"),
    ],
  },
  {
    id: "p-ibrahim",
    firstName: "Ibrahim",
    lastName: "Hassan",
    preferredName: "Ibrahim",
    age: 36,
    pronouns: "he/him",
    centre: "Manchester",
    localAuthority: "Manchester",
    advisorId: "adv-sarah",
    programme: "Future Employment Support",
    ucStatus: "Universal Credit",
    referralSource: "Homelessness pathway · LA",
    referralDate: "2026-06-01",
    stage: "support",
    risk: "high",
    barriers: [
      { id: "b1", label: "Recent homelessness — now in supported housing", kind: "non-vocational" },
      { id: "b2", label: "Recovery — keep evenings free for group", kind: "non-vocational" },
    ],
    assessment: { life: 36, skills: 58, work: 40, aspirations: 63 },
    goal: "Kitchen porter with a chef pathway",
    availability: "Days only",
    lastContact: "2026-08-28",
    nextAction: "Re-engage — 20 days since last contact",
    daysOnProgramme: 108,
    jobsApplied: 1,
    interviews: 0,
    engagement: 18,
    phone: "07700 900 771",
    email: "ibrahim.h@example.test",
    plan: "Stabilise housing and recovery first. Kitchen trial shift only when keyworker agrees.",
    cvSummary: "Kitchen experience in Sudan and two London restaurants. Hard-working, early, calm under heat.",
    notes: [
      n(
        "Sarah Bell",
        "2026-08-28",
        "Missed last two appointments. Keyworker says housing is noisy. Do not close — try a walk-in at the centre with food offered.",
      ),
    ],
    actions: [
      act("i1", "Re-engagement visit with keyworker", "2026-09-17", "advisor"),
    ],
  },
];

export const INTERVENTIONS: Intervention[] = [
  {
    id: "int-1",
    participantId: "p-amina",
    title: "Excel essentials (group)",
    kind: "Skills",
    status: "in-progress",
    scheduled: "2026-09-18",
    owner: "Skills coach",
    notes: "Session 2 of 4",
  },
  {
    id: "int-2",
    participantId: "p-amina",
    title: "Mock interview — admin",
    kind: "Interview",
    status: "planned",
    scheduled: "2026-09-22",
    owner: "Sarah Bell",
    notes: "20 minutes, structured questions",
  },
  {
    id: "int-3",
    participantId: "p-fatima",
    title: "Care Certificate",
    kind: "Skills",
    status: "in-progress",
    scheduled: "2026-09-18",
    owner: "Health academy",
    notes: "Unit 2",
  },
  {
    id: "int-4",
    participantId: "p-nia",
    title: "Interview simulation",
    kind: "Interview",
    status: "planned",
    scheduled: "2026-09-24",
    owner: "Sarah Bell",
    notes: "Quiet room, questions in advance",
  },
  {
    id: "int-5",
    participantId: "p-michael",
    title: "Supported digital job search",
    kind: "Digital",
    status: "planned",
    scheduled: "2026-09-18",
    owner: "Marcus Reid",
    notes: "Library, 90 minutes",
  },
  {
    id: "int-6",
    participantId: "p-chloe",
    title: "Confidence group (youth)",
    kind: "Wellbeing",
    status: "planned",
    scheduled: "2026-09-25",
    owner: "Youth coach",
    notes: "",
  },
  {
    id: "int-7",
    participantId: "p-james",
    title: "Employer introduction — DHL",
    kind: "Employer",
    status: "planned",
    scheduled: "2026-09-19",
    owner: "Marcus Reid",
    notes: "Coordinator vacancy",
  },
  {
    id: "int-8",
    participantId: "p-ibrahim",
    title: "Re-engagement with keyworker",
    kind: "Engagement",
    status: "planned",
    scheduled: "2026-09-17",
    owner: "Sarah Bell",
    notes: "High priority",
  },
];

export const JOBS: JobVacancy[] = [
  {
    id: "job-1",
    title: "School office administrator",
    employer: "Longsight Community Primary",
    location: "Manchester · 0.8 mi",
    salary: "£24,100 – £25,400",
    hours: "Term-time, 09:00–14:30",
    posted: "2026-09-12",
    skills: ["administration", "phones", "diary", "parents"],
    inclusive: ["School hours", "Disability Confident"],
    summary:
      "Front-of-house school office. Parents, registers, and a calm presence at the hatch. Term-time only.",
  },
  {
    id: "job-2",
    title: "HR assistant (part-time)",
    employer: "Greater Manchester Combined Authority",
    location: "Manchester city · hybrid 2 days",
    salary: "£26,000 FTE",
    hours: "22.5 hours, school-friendly",
    posted: "2026-09-10",
    skills: ["administration", "HR", "Excel", "confidentiality"],
    inclusive: ["Hybrid", "Disability Confident Leader"],
    summary:
      "Supporting onboarding paperwork and a shared inbox. Quiet office, structured work.",
  },
  {
    id: "job-3",
    title: "Warehouse coordinator",
    employer: "DHL Supply Chain",
    location: "Bordesley Green · Birmingham",
    salary: "£28,500 + shift premium",
    hours: "Days, sitting/standing mix",
    posted: "2026-09-08",
    skills: ["logistics", "rotas", "health and safety", "leadership"],
    inclusive: ["Reasonable adjustments", "Ban the box"],
    summary:
      "Coordinate a day shift. Not a picker role. Office-side of the warehouse with floor time.",
  },
  {
    id: "job-4",
    title: "Healthcare support worker",
    employer: "Barts Health NHS Trust",
    location: "Whitechapel",
    salary: "Band 2 · £24,000+",
    hours: "Early and late, no nights required",
    posted: "2026-09-05",
    skills: ["care", "communication", "reliability"],
    inclusive: ["NHS", "Guaranteed interview scheme"],
    summary:
      "Ward support. Full training. Values-based interview.",
  },
  {
    id: "job-5",
    title: "IT service desk apprentice",
    employer: "Manchester City Council",
    location: "Manchester · hybrid",
    salary: "£22,400",
    hours: "Full-time, quiet office option",
    posted: "2026-09-11",
    skills: ["IT support", "ticketing", "patience", "written"],
    inclusive: ["Disability Confident Leader", "Neuroinclusive"],
    summary:
      "First-line tickets for council staff. Structured training. Headphones allowed.",
  },
  {
    id: "job-6",
    title: "Class 2 driver",
    employer: "Newham Council fleet",
    location: "Beckton depot",
    salary: "£32,000",
    hours: "Early days",
    posted: "2026-09-09",
    skills: ["HGV", "safety", "local knowledge"],
    inclusive: ["Public sector", "Bus routes to depot"],
    summary:
      "Refuse and bulk collections. Depot on the 147 and 376.",
  },
  {
    id: "job-7",
    title: "Kitchen porter",
    employer: "The Refuge",
    location: "Manchester city",
    salary: "£12.60 / hour + meals",
    hours: "Days, 08:00–16:00",
    posted: "2026-09-13",
    skills: ["kitchen", "pace", "team"],
    inclusive: ["Ban the box", "Meals provided"],
    summary:
      "Daytime kitchen. Training chef pathway after 12 weeks.",
  },
  {
    id: "job-8",
    title: "Retail advisor",
    employer: "John Lewis Stratford",
    location: "Stratford",
    salary: "£12.85 / hour",
    hours: "Part-time, weekends available",
    posted: "2026-09-06",
    skills: ["customer service", "retail", "till"],
    inclusive: ["Youth friendly", "Staff discount"],
    summary:
      "Home department. Structured onboarding. Good first job.",
  },
  {
    id: "job-9",
    title: "Bookkeeping assistant",
    employer: "Harborne Medical Practice",
    location: "Birmingham",
    salary: "£25,200 FTE",
    hours: "18 hours, Tue–Thu",
    posted: "2026-09-04",
    skills: ["bookkeeping", "AAT", "confidentiality", "NHS"],
    inclusive: ["Part-time", "Caring-friendly"],
    summary:
      "GP practice finance. Quiet, predictable, three days.",
  },
  {
    id: "job-10",
    title: "Grounds operative",
    employer: "Sandwell MBC",
    location: "West Bromwich",
    salary: "£24,900",
    hours: "Days",
    posted: "2026-09-01",
    skills: ["grounds", "outdoor", "plant"],
    inclusive: ["Local authority", "Vehicle provided"],
    summary:
      "Parks and estates. Daytime. Van comes with the role.",
  },
];

export const WORKFLOW: WorkflowTask[] = [
  {
    id: "w1",
    participantId: "p-ryan",
    title: "First appointment — ID and disclosure",
    column: "referrals",
    priority: "now",
    due: "2026-09-18",
  },
  {
    id: "w2",
    participantId: "p-chloe",
    title: "Complete onboarding and joint pledge",
    column: "referrals",
    priority: "soon",
    due: "2026-09-19",
  },
  {
    id: "w3",
    participantId: "p-ibrahim",
    title: "Re-engage — 20 days since contact",
    column: "contact",
    priority: "now",
    due: "2026-09-17",
  },
  {
    id: "w4",
    participantId: "p-priya",
    title: "Overdue wellbeing check-in",
    column: "contact",
    priority: "now",
    due: "2026-09-17",
  },
  {
    id: "w5",
    participantId: "p-nia",
    title: "Finish four-pillar assessment",
    column: "assessments",
    priority: "soon",
    due: "2026-09-18",
  },
  {
    id: "w6",
    participantId: "p-chloe",
    title: "First assessment session",
    column: "assessments",
    priority: "soon",
    due: "2026-09-19",
  },
  {
    id: "w7",
    participantId: "p-amina",
    title: "Mock interview — admin",
    column: "interventions",
    priority: "soon",
    due: "2026-09-22",
  },
  {
    id: "w8",
    participantId: "p-james",
    title: "DHL employer introduction",
    column: "interventions",
    priority: "now",
    due: "2026-09-19",
  },
  {
    id: "w9",
    participantId: "p-michael",
    title: "Library digital session",
    column: "interventions",
    priority: "soon",
    due: "2026-09-18",
  },
  {
    id: "w10",
    participantId: "p-david",
    title: "Week-4 in-work check",
    column: "outcomes",
    priority: "watch",
    due: "2026-09-18",
  },
  {
    id: "w11",
    participantId: "p-sophie",
    title: "13-week evidence pack",
    column: "outcomes",
    priority: "soon",
    due: "2026-09-20",
  },
];

export const INTEGRATIONS: Integration[] = [
  {
    id: "i1",
    name: "DWP / Universal Credit",
    category: "Government",
    status: "connected",
    detail: "Referral ingest, UC status, and outcome reporting. PRaP-style payloads.",
  },
  {
    id: "i2",
    name: "Jobcentre Plus",
    category: "Government",
    status: "connected",
    detail: "Work coach referrals, DNA flags, and two-way case notes.",
  },
  {
    id: "i3",
    name: "Find a Job",
    category: "Vacancies",
    status: "connected",
    detail: "Vacancy feed with location and hours filters for matching.",
  },
  {
    id: "i4",
    name: "GOV.UK Notify",
    category: "Engagement",
    status: "connected",
    detail: "SMS and email for appointments, DNA nudges, and job alerts.",
  },
  {
    id: "i5",
    name: "Employer CRM",
    category: "Employers",
    status: "ready",
    detail: "Account-managed vacancies, warm intros, and vacancy inclusivity flags.",
  },
  {
    id: "i6",
    name: "iWorks (legacy)",
    category: "Migration",
    status: "migrating",
    detail: "Read-only historic case files. Cutover planned with the FES MVP.",
  },
  {
    id: "i7",
    name: "Interview simulation",
    category: "Learning",
    status: "ready",
    detail: "Structured interview practice with speech feedback for advisors.",
  },
  {
    id: "i8",
    name: "Local authority housing",
    category: "Partners",
    status: "ready",
    detail: "Keyworker flags for homelessness and temporary accommodation.",
  },
];

export const PROGRAMME_KPIS: ProgrammeKpis = {
  activeCaseload: 1847,
  referrals30d: 142,
  jobStarts30d: 96,
  sustainment13: 71,
  sustainment26: 58,
  dnaRate: 8.4,
  avgDaysToJob: 64,
  selfServiceWeekly: 61,
  atRisk: 118,
  overdueContacts: 47,
};

export const MONTHLY_STARTS = [
  { month: "Mar", starts: 71, referrals: 128 },
  { month: "Apr", starts: 78, referrals: 135 },
  { month: "May", starts: 84, referrals: 141 },
  { month: "Jun", starts: 81, referrals: 138 },
  { month: "Jul", starts: 90, referrals: 150 },
  { month: "Aug", starts: 94, referrals: 147 },
  { month: "Sep", starts: 96, referrals: 142 },
];

export const FUNNEL = [
  { stage: "Referred", value: 2400 },
  { stage: "Onboarded", value: 2180 },
  { stage: "Assessed", value: 2010 },
  { stage: "In support", value: 1847 },
  { stage: "Job start", value: 612 },
  { stage: "13-week", value: 434 },
  { stage: "26-week", value: 355 },
];

export const CENTRE_PERFORMANCE = [
  { centre: "Manchester", caseload: 640, starts: 38, sustain: 73, dna: 7.1 },
  { centre: "Birmingham", caseload: 572, starts: 31, sustain: 69, dna: 9.2 },
  { centre: "London", caseload: 635, starts: 27, sustain: 71, dna: 8.8 },
];
