/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ParticipantRouteImport } from './routes/participant'
import { Route as AdvisorIndexRouteImport } from './routes/advisor/index'
import { Route as AdvisorCaseloadRouteImport } from './routes/advisor/caseload'
import { Route as AdvisorWorkflowRouteImport } from './routes/advisor/workflow'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as OpsIntegrationsRouteImport } from './routes/ops/integrations'
import { Route as ParticipantIndexRouteImport } from './routes/participant/index'
import { Route as ParticipantCoachRouteImport } from './routes/participant/coach'
import { Route as ParticipantJobsRouteImport } from './routes/participant/jobs'
import { Route as ParticipantPlanRouteImport } from './routes/participant/plan'
import { Route as AdvisorParticipantsParticipantIdRouteImport } from './routes/advisor/participants.$participantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantRoute = ParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorCaseloadRoute = AdvisorCaseloadRouteImport.update({
  id: '/caseload',
  path: '/caseload',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorWorkflowRoute = AdvisorWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AdvisorRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsIntegrationsRoute = OpsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => OpsRoute,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantCoachRoute = ParticipantCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantJobsRoute = ParticipantJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantPlanRoute = ParticipantPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => ParticipantRoute,
} as any)
const AdvisorParticipantsParticipantIdRoute =
  AdvisorParticipantsParticipantIdRouteImport.update({
    id: '/participants/$participantId',
    path: '/participants/$participantId',
    getParentRoute: () => AdvisorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/participant': typeof ParticipantRouteWithChildren
  '/advisor/caseload': typeof AdvisorCaseloadRoute
  '/advisor/workflow': typeof AdvisorWorkflowRoute
  '/ops/integrations': typeof OpsIntegrationsRoute
  '/participant/coach': typeof ParticipantCoachRoute
  '/participant/jobs': typeof ParticipantJobsRoute
  '/participant/plan': typeof ParticipantPlanRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/advisor/participants/$participantId': typeof AdvisorParticipantsParticipantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor/caseload': typeof AdvisorCaseloadRoute
  '/advisor/workflow': typeof AdvisorWorkflowRoute
  '/ops/integrations': typeof OpsIntegrationsRoute
  '/participant/coach': typeof ParticipantCoachRoute
  '/participant/jobs': typeof ParticipantJobsRoute
  '/participant/plan': typeof ParticipantPlanRoute
  '/advisor': typeof AdvisorIndexRoute
  '/ops': typeof OpsIndexRoute
  '/participant': typeof ParticipantIndexRoute
  '/advisor/participants/$participantId': typeof AdvisorParticipantsParticipantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/participant': typeof ParticipantRouteWithChildren
  '/advisor/caseload': typeof AdvisorCaseloadRoute
  '/advisor/workflow': typeof AdvisorWorkflowRoute
  '/ops/integrations': typeof OpsIntegrationsRoute
  '/participant/coach': typeof ParticipantCoachRoute
  '/participant/jobs': typeof ParticipantJobsRoute
  '/participant/plan': typeof ParticipantPlanRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/advisor/participants/$participantId': typeof AdvisorParticipantsParticipantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/ops'
    | '/participant'
    | '/advisor/caseload'
    | '/advisor/workflow'
    | '/ops/integrations'
    | '/participant/coach'
    | '/participant/jobs'
    | '/participant/plan'
    | '/advisor/'
    | '/ops/'
    | '/participant/'
    | '/advisor/participants/$participantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor/caseload'
    | '/advisor/workflow'
    | '/ops/integrations'
    | '/participant/coach'
    | '/participant/jobs'
    | '/participant/plan'
    | '/advisor'
    | '/ops'
    | '/participant'
    | '/advisor/participants/$participantId'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/ops'
    | '/participant'
    | '/advisor/caseload'
    | '/advisor/workflow'
    | '/ops/integrations'
    | '/participant/coach'
    | '/participant/jobs'
    | '/participant/plan'
    | '/advisor/'
    | '/ops/'
    | '/participant/'
    | '/advisor/participants/$participantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  ParticipantRoute: typeof ParticipantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant': {
      id: '/participant'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof ParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/caseload': {
      id: '/advisor/caseload'
      path: '/caseload'
      fullPath: '/advisor/caseload'
      preLoaderRoute: typeof AdvisorCaseloadRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/workflow': {
      id: '/advisor/workflow'
      path: '/workflow'
      fullPath: '/advisor/workflow'
      preLoaderRoute: typeof AdvisorWorkflowRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/integrations': {
      id: '/ops/integrations'
      path: '/integrations'
      fullPath: '/ops/integrations'
      preLoaderRoute: typeof OpsIntegrationsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/participant/': {
      id: '/participant/'
      path: '/'
      fullPath: '/participant/'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/coach': {
      id: '/participant/coach'
      path: '/coach'
      fullPath: '/participant/coach'
      preLoaderRoute: typeof ParticipantCoachRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/jobs': {
      id: '/participant/jobs'
      path: '/jobs'
      fullPath: '/participant/jobs'
      preLoaderRoute: typeof ParticipantJobsRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/plan': {
      id: '/participant/plan'
      path: '/plan'
      fullPath: '/participant/plan'
      preLoaderRoute: typeof ParticipantPlanRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/advisor/participants/$participantId': {
      id: '/advisor/participants/$participantId'
      path: '/participants/$participantId'
      fullPath: '/advisor/participants/$participantId'
      preLoaderRoute: typeof AdvisorParticipantsParticipantIdRouteImport
      parentRoute: typeof AdvisorRoute
    }
  }
}

interface AdvisorRouteChildren {
  AdvisorCaseloadRoute: typeof AdvisorCaseloadRoute
  AdvisorWorkflowRoute: typeof AdvisorWorkflowRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
  AdvisorParticipantsParticipantIdRoute: typeof AdvisorParticipantsParticipantIdRoute
}

const AdvisorRouteChildren: AdvisorRouteChildren = {
  AdvisorCaseloadRoute: AdvisorCaseloadRoute,
  AdvisorWorkflowRoute: AdvisorWorkflowRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
  AdvisorParticipantsParticipantIdRoute: AdvisorParticipantsParticipantIdRoute,
}

const AdvisorRouteWithChildren =
  AdvisorRoute._addFileChildren(AdvisorRouteChildren)

interface OpsRouteChildren {
  OpsIntegrationsRoute: typeof OpsIntegrationsRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsIntegrationsRoute: OpsIntegrationsRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface ParticipantRouteChildren {
  ParticipantCoachRoute: typeof ParticipantCoachRoute
  ParticipantJobsRoute: typeof ParticipantJobsRoute
  ParticipantPlanRoute: typeof ParticipantPlanRoute
  ParticipantIndexRoute: typeof ParticipantIndexRoute
}

const ParticipantRouteChildren: ParticipantRouteChildren = {
  ParticipantCoachRoute: ParticipantCoachRoute,
  ParticipantJobsRoute: ParticipantJobsRoute,
  ParticipantPlanRoute: ParticipantPlanRoute,
  ParticipantIndexRoute: ParticipantIndexRoute,
}

const ParticipantRouteWithChildren = ParticipantRoute._addFileChildren(
  ParticipantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  ParticipantRoute: ParticipantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
